services:
  # 1. Брокер сообщений (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. База данных (Общая для сервисов)
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: zhuanz
      POSTGRES_DB: payment_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  # 3. Кэш и хранилище состояний (НОВОЕ для Assignment 4)
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 4. Payment Service (gRPC Server + RabbitMQ Producer)
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "50051:50051"
    environment:
      DB_URL: "postgres://zhuanz:password@postgres:5432/payment_db?sslmode=disable"
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  # 5. Notification Service (Background Worker + Adapter + Retries)
  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      REDIS_ADDR: "redis:6379" # Для идемпотентности заданий
      PROVIDER_MODE: "SIMULATED" # Режим: REAL или SIMULATED
      MAX_RETRIES: 3 # Максимальное количество попыток
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  # 6. Order Service (HTTP API + gRPC Client + Redis Caching)
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8080"
    environment:
      DB_URL: "postgres://zhuanz:password@postgres:5432/payment_db?sslmode=disable"
      HTTP_PORT: "8080"
      PAYMENT_SERVICE_ADDR: "payment-service:50051"
      REDIS_ADDR: "redis:6379" # Для паттерна Cache-aside
      CACHE_TTL: "300s" # Время жизни кэша (5 минут)
    depends_on:
      - postgres
      - payment-service
      - redis